INSERT [dbo].[Course] ([Id], [Name], [Description], [EstimatedDuration], [TeacherId], [CategoryId]) VALUES (7, N'Mike''s Course', N'Mike''s Course Description', 26, 4, 11)



INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (17, 7,  1, N'Course Introduction')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (18, 7,  2, N'Setup and First Steps')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (19, 7,  3, N'Variables, Datatypes and Operators')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (20, 7,  4, N'Java Tutorial: Expressions, Statements, Code blocks, Methods and more')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (21, 7,  5, N'Control Flow Statements')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (22, 7,  6, N'OOP Part 1 - Classes, Constructors and Inheritance')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (23, 7,  7, N'OOP Part 2 - Composition, Encapsulation, and Polymorphism')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (24, 7,  8, N'Arrays, Java inbuilt Lists, Autoboxing and Unboxing')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (25, 7,  9, N'Inner and Abstract Classes & Interfaces')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (26, 7, 10, N'Java Generics')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (27, 7, 11, N'Naming Conventions and Packages. static and final keywords')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (28, 7, 12, N'Java Collections')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (29, 7, 13, N'JavaFX')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (30, 7, 14, N'Basic Input & Output including java.util')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (31, 7, 15, N'Concurrency in Java')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (32, 7, 16, N'Lambda Expressions')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (33, 7, 17, N'Regular Expressions')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (34, 7, 18, N'Debugging and Unit Testing')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (35, 7, 19, N'Databases')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (36, 7, 20, N'Java Network Programming')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (37, 7, 21, N'Java 9 Module System')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (38, 7, 22, N'Migrating Java Projects to Java 9')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (39, 7, 23, N'Archived Videos')
INSERT [dbo].[Curricula] ([Id], [CourseId], [CourseSession], [Description]) VALUES (40, 7, 24, N'Bonus Material')

INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  1, N'Course Introduction')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  2, N'Setup and First Steps')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  3, N'Variables, Datatypes and Operators')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  4, N'Java Tutorial: Expressions, Statements, Code blocks, Methods and more')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  5, N'Control Flow Statements')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  6, N'OOP Part 1 - Classes, Constructors and Inheritance')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  7, N'OOP Part 2 - Composition, Encapsulation, and Polymorphism')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  8, N'Arrays, Java inbuilt Lists, Autoboxing and Unboxing')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  9, N'Inner and Abstract Classes & Interfaces')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 10, N'Java Generics')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 11, N'Naming Conventions and Packages. static and final keywords')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 12, N'Java Collections')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 13, N'JavaFX')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 14, N'Basic Input & Output including java.util')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 15, N'Concurrency in Java')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 16, N'Lambda Expressions')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 17, N'Regular Expressions')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 18, N'Debugging and Unit Testing')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 19, N'Databases')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 20, N'Java Network Programming')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 21, N'Java 9 Module System')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 22, N'Migrating Java Projects to Java 9')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 23, N'Archived Videos')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19, 24, N'Bonus Material')

INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  1, N'Install and Setup for Mac and Windows')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  2, N'Strings - Working with Textual Data')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  3, N'Integers and Floats - Working with Numeric Data')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  4, N'Lists, Tuples, and Sets')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  5, N'Dictionaries - Working with Key-Value Pairs')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  6, N'Conditionals and Booleans - If, Else, and Elif Statements')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  7, N'Loops and Iterations - For/While Loops')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  8, N'Functions')
INSERT [dbo].[Curricula] ( [CourseId], [CourseSession], [Description]) VALUES ( 19,  9, N'Import Modules and Exploring The Standard Library')

INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 49, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=YYXdXT2l-Gg')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 50, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=k9TUPpGqYTo')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 51, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=khKv-8q7YmY')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 52, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=W8KRzm-HUcc')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 53, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=daefaLgNkw0')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 54, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=DZwmZ8Usvnk')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 55, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=6iF8Xb7Z3wQ')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 56, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=9Os0o3wzS_I')
INSERT [dbo].[CurriculaLineItem] ( [CurriculaId], [CurriculaTypeId], [Description], [LineItem], [URL] ) VALUES ( 57, 1, N'Play Video', 1, N'https://www.youtube.com/watch?v=CqvZ3vGoGs0')







